image: mcr.microsoft.com/dotnet/sdk:6.0

stages: 
     - test
# build:
#   stage: build
#   script:
#     - 'dotnet build --no-restore'
tests:
  stage: test
  script:
    - cd TestTotal
    - dotnet build
    - dotnet test
# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
